---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: copy deploy_key to id_rsa
  environment:
    SSH_KEY:
      from_secret: deploy_key
  commands:
    - mkdir ~/.ssh
    - echo "$SSH_KEY" >> ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-keyscan lounge.rocks >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-add ~/.ssh/id_rsa

- name: Show flake info
  commands:
  - nix flake show
  - nix flake metadata
  - nix flake check

- name: Build laptop
  commands:
  - nix build -v '.#nixosConfigurations.laptop.config.system.build.toplevel' --show-trace

- name: Build arm
  commands:
  - nix build -v '.#nixosConfigurations.arm.config.system.build.toplevel' --show-trace

- name: Build pi4b
  commands:
  - nix build -v '.#nixosConfigurations.pi4b.config.system.build.toplevel' --show-trace

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build flake update

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: create result-old files
  commands:
  - nix build -v '.#nixosConfigurations.laptop.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result laptop-old
  - nix build -v '.#nixosConfigurations.arm.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result arm-old
  - nix build -v '.#nixosConfigurations.pi4b.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result pi4b-old

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Build laptop
  commands:
  - nix build -v '.#nixosConfigurations.laptop.config.system.build.toplevel'
  - mv result laptop-new

- name: Build arm
  commands:
  - nix build -v '.#nixosConfigurations.arm.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result arm-new

- name: Build pi4b
  commands:
  - nix build -v '.#nixosConfigurations.pi4b.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result pi4b-new

- name: Print report
  commands:
  - echo "laptop:" && nix store diff-closures $(readlink -f laptop-old) $(readlink -f laptop-new)
  - echo "arm:" && nix store diff-closures $(readlink -f arm-old) $(readlink -f arm-new)
  - echo "pi4b:" && nix store diff-closures $(readlink -f pi4b-old) $(readlink -f pi4b-new)

trigger:
  branch:
  - main
  event:
  - pull_request
  - cron
